### ISSUE TITLE
Program not functioning correctly

### ISSUE THREAD

**Issue by ualbertagreen** [EyeTribe/tet-csharp-samples#5]
not sure if I've got some build configuration wrong or something but most of the functionalities doesn't seem to work. 

Details in this forum thread. 
[http://theeyetribe.com/forum/viewtopic.php?f=11&t=647&sid=ccf1cf57629b8d0cb7dc197d570a14d5](url)

**Comment by Hskovsgaard** [comment]
Can you please elaborate which server version you are using.
I cloned the samples repository and build the calibration and scroll samples. Both samples worked just fine with our last official SDK version (v.0.9.77) installed.

**Comment by ualbertagreen** [comment]
I think I was using v0.9.56 of the server. I just reinstalled the SDK and it works now. Thanks.

**Comment by Hskovsgaard** [comment]
Happy to read that the latest SDK fixed your issue.
